const assert = require('node:assert/strict');
const {VisionPanel} = require('../web/public/vision-ui.js');
let now = 0;
const elements = new Map();
const document = {getElementById(id) {
    if (!elements.has(id)) elements.set(id,{textContent:'',title:''});
    return elements.get(id);
}};
const panel = new VisionPanel(document,()=>now);
const base = {status:'ok',person_detected:true,enrolled:true,identity:'Master',emotion:'happy',emotion_confidence:.82,head_action:'unknown',arm_action:'unknown'};
const send = (status,t) => {now=t;panel.receive({...base,...status});panel.tick();};
send({},0); send({},750);
assert.equal(elements.get('cv-emotion').textContent,'Vui (82%)');
for (let t=1000;t<2500;t+=250) send({emotion:t%500===0?'unknown':'happy'},t);
assert.equal(elements.get('cv-emotion').textContent,'Vui (82%)','brief unknown must not blink');
send({head_action:'head_nod'},2500);
send({},3000);
assert.equal(elements.get('cv-action').textContent,'Gật đầu','short gesture must remain readable');
send({},4500);
assert.equal(elements.get('cv-action').textContent,'Chưa rõ');
send({emotion:'unknown'},4750);send({emotion:'unknown'},6500);
assert.equal(elements.get('cv-emotion').textContent,'Chưa rõ','persistent uncertainty must expire');
send({emotion_probs:{happy:.60,neutral:.30,surprised:.10}},7000);
assert.equal(elements.get('cv-emotion').textContent,'Vui (60%)\nTrung tính (30%)\nNgạc nhiên (10%)');
send({emotion_probs:{happy:.30,neutral:.25,surprised:.15,sad:.10,angry:.08,disgust:.06,fear:.04,contempt:.02}},7250);
assert.equal(elements.get('cv-emotion').textContent,'Vui (30%)\nTrung tính (25%)\nNgạc nhiên (15%)\nBuồn (10%)\nGiận (8%)','only the top five emotions must be shown');
send({emotion_probs:{happy:.60,neutral:.30,surprised:.10},emotion_scores:{sad:.45,angry:.30,neutral:.25}},7500);
assert.equal(elements.get('cv-emotion').textContent,'Buồn (45%)\nGiận (30%)\nTrung tính (25%)','fused scores should drive the main ranking');
now=11750;panel.tick();
assert.equal(elements.get('cv-health').textContent,'Mất kết nối Vision');
assert.equal(elements.get('cv-identity').textContent,'Chưa rõ');
console.log('Vision UI: smoothing, event hold, uncertainty expiry and disconnection passed');
send({actions:[{channel:'head',label:'head_shake'},{channel:'arms',label:'hand_raised'},{channel:'left_hand',label:'victory'},{channel:'right_hand',label:'thumbs_up'}],emotion_probs:{happy:.82,sad:.15},expression_intensities:{fear:.6},eyes:{state:'open',gaze:'toward_camera',blink_rate_per_min:12},distance:{cm:61,source:'assumed_fov'}},12000);
assert.equal(elements.get('cv-head').textContent,'Lắc đầu');
assert.equal(elements.get('cv-arms').textContent,'Giơ một tay');
assert.equal(elements.get('cv-left-hand').textContent,'Hai ngón V / hello');
assert.equal(elements.get('cv-right-hand').textContent,'Ngón cái / like');
assert.equal(elements.get('cv-score-happy').textContent,'82%');
assert.equal(elements.get('cv-intensity-score-fear').textContent,'60%');
now=17000;panel.tick();
assert.equal(elements.get('cv-score-happy').textContent,'—');
assert.equal(elements.get('cv-left-hand').textContent,'Chưa rõ');
console.log('Vision UI: simultaneous actions, continuous scores and stale clearing passed');
send({actions:[{channel:'head',label:'head_tilt_left'},{channel:'arms',label:'arms_crossed'},
    {channel:'left_hand',label:'ok_sign'}],objects:[{label:'scissors'},{label:'teddy bear'}]},17250);
assert.equal(elements.get('cv-head').textContent,'Nghiêng đầu trái');
assert.equal(elements.get('cv-arms').textContent,'Khoanh tay');
assert.equal(elements.get('cv-left-hand').textContent,'Dấu OK');
send({objects:[{label:'scissors'},{label:'teddy bear'}]},17800);
assert.equal(elements.get('cv-objects').textContent,'Kéo, Gấu bông');
send({objects:[{label:'cup',confidence:.86},{label:'cup',confidence:.74}]},18000);
assert.equal(elements.get('cv-objects').textContent,'Kéo, Gấu bông, Ly/cốc ×2 (86%)');
send({actions:[{channel:'right_hand',label:'thumbs_down',associated:false}],objects:[]},18250);
assert.equal(elements.get('cv-right-hand').textContent,'Không thích / ngón cái xuống');
now=20750;panel.tick();
assert.notEqual(elements.get('cv-objects').textContent,'Chưa thấy','a brief detection remains visible for three seconds');
now=21250;panel.tick();
assert.equal(elements.get('cv-objects').textContent,'Chưa thấy');
send({hands:[{side:'left',gesture:'unknown',gesture_candidate:'open_palm',extended_fingers:4,confidence:.91,associated:false}]},21500);
assert.equal(elements.get('cv-left-hand').textContent,'Đang xác nhận: Xòe bàn tay · 91%');
send({hands:[{side:'right',gesture:'unknown',gesture_candidate:'unknown',extended_fingers:2,confidence:.77,associated:false}]},21750);
assert.equal(elements.get('cv-right-hand').textContent,'Đã thấy bàn tay · 2 ngón duỗi · 77%');
console.log('Vision UI: expanded gesture and object labels passed');
